#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           16
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^3'
bspc rule -a Kupfer.py focus=oj
bspc rule -a Screenkey manage=off
bspc rule -a Lightscreen state=floating rectangle=300x120
